#!/usr/bin/python3
import cgi  
import cgitb
import MySQLdb
import passwords
cgitb.enable()




print("Status: 200 OK")
print('Content-Type: text/html\n\n')
print()
print()


conn = MySQLdb.connect(host = passwords.SQL_HOST,
user = passwords.SQL_USER,
passwd = passwords.SQL_PASSWD,
db = "mydb")

cursor = conn.cursor()

#1
cursor.execute("SELECT * FROM orders;")

results = cursor.fetchall()
cursor.close()
conn.commit()
conn.close()
output = ''

rows = len(results)
if (rows > 0):
    cols = len(results[0])
    #2
    output += '''<table style="width:100%"><tr><th>Order Number</th><th>Product Number</th><th>Date</th><th>First Name</th><th>Last Name</th></tr>'''
    for r in range(rows):
        output += '<tr>'
        for c in range(cols):
            output += '<td>' + str(results[r][c]) + '</td>'
        output += '</tr>'
    output += '</table>'

else:
    #3
    output += 'No orders at this time'

output += '<br> returned ' + str(rows) + ' rows.'
#4
print('''<html>
<head>
<title>Orders</title>
<style>
td {
text-align: center;
}
</style>
</head>

<body>

''' + output + '''
<br>
<a href='/'>Home</a>

</body>
</html>''')
