#!/usr/bin/python3
import cgi  
import cgitb
import MySQLdb
import passwords
import os
import json
import sys
cgitb.enable()


conn = MySQLdb.connect(host = passwords.SQL_HOST,
user = passwords.SQL_USER,
passwd = passwords.SQL_PASSWD,
db = "vet")
cursor = conn.cursor()

'''
print("Status: 200 OK")
print("Content-Type: application/json")
print()
'''

def make_json(head, tup):
    d = {}
    for i in range(len(head)):
        d[head[i]] = tup[i]
    return d


def post_people(cursor):
    input_data = sys.stdin.read()
    d = json.loads(input_data)
    keys = set(d.keys())
    fields = set(['fname','lname','age'])
    omitted = fields - keys
    for key in omitted:
        d[key]='N/A'
    try:
        cursor.execute('''insert into people (fname, lname, age) values
        ('{}','{}','{}');'''.format(d['fname'], d['lname'], d['age']))
        cursor.close()
        conn.commit()
        conn.close()
        print("Status: 302 Redirect")
        print("Location: http://ec2-54-162-228-22.compute-1.amazonaws.com/cgi-bin/people/")
        print()
    except:
        print("Status: 200 OK")
        print("Content-Type: text/html")
        print()
        raise

def get_people(cursor):
    cursor.execute('select * from people;')
    lis = []
    field_names = [i[0] for i in cursor.description]
    for row in cursor.fetchall():
        j = make_json(field_names, row)
        idd = str(j['id'])
        j['link'] = 'http://ec2-54-162-228-22.compute-1.amazonaws.com/cgi-bin/people/'+idd
        lis.append(j)
    print("Status: 200 OK")
    print("Content-Type: application/json")
    print()
    print(json.dumps(lis, indent=2))
    cursor.close()
    conn.commit()
    conn.close()

def get_person(cursor, path): 
    cursor.execute('select * from people where id={};'.format(path))
    field_names = [i[0] for i in cursor.description]
    for row in cursor.fetchall():
        j = make_json(field_names, row)
        idd = str(j['id'])
        j['link'] = 'http://ec2-54-162-228-22.compute-1.amazonaws.com/cgi-bin/people/'+idd
        print("Status: 200 OK")
        print("Content-Type: application/json")
        print()
        print(json.dumps(j, indent=1))
    cursor.close()
    conn.commit()
    conn.close()

def del_person(cursor, path):
    try:
        cursor.execute('delete from pets where owner={}'.format(path))
        cursor.execute('delete from people where id={};'.format(path))
        cursor.close()
        conn.commit()
        conn.close()
        print("Status: 302 Redirect")
        print("Location: http://ec2-54-162-228-22.compute-1.amazonaws.com/cgi-bin/people/")
        print()
    except:
        print("Status: 404 Not Found")
        print("Content-Type: text/html")
        print()
        raise

request = os.environ["REQUEST_METHOD"]

if "PATH_INFO" in os.environ and os.environ["PATH_INFO"] != '/':
    #specific person
    path = os.environ["PATH_INFO"].strip('/')
    if request == "GET":
        get_person(cursor, path)
    elif request == "DELETE":
        del_person(cursor, path)
    else:
        print('Status: 405 Method Not Allowed')
        print("Content-Type: text/html")
        print()

else:
    #people
    path = '/'
    if request == "GET":
        get_people(cursor)
    elif request == "POST":
        post_people(cursor)
    else:
        print('Status: 405 Method Not Allowed')
        print("Content-Type: text/html")
        print()


